//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuongBanDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnhSanPham
    {
        public int MaHinhAnh { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public string DuongDanAnh { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
