//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuongBanDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyenHan
    {
        public QuyenHan()
        {
            this.VaiTroes = new HashSet<VaiTro>();
        }
    
        public int MaQuyen { get; set; }
        public string TenQuyen { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<VaiTro> VaiTroes { get; set; }
    }
}
