//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuongBanDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.GioHangs = new HashSet<GioHang>();
            this.HinhAnhSanPhams = new HashSet<HinhAnhSanPham>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public decimal GiaBan { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string MoTaTongQuan { get; set; }
        public string ThongSoKyThuat { get; set; }
        public string AnhChinh { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual ICollection<HinhAnhSanPham> HinhAnhSanPhams { get; set; }
    }
}
